version: '3'

services:
  venue-app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    command: sh -c "yarn install && yarn dev"